$(document).ready(function() {
    $("html").click(function(event){
        var tgtbtnit = event.target.id;

        if(tgtbtnit == "about-felicific") {
          $("#knowmore").html("<div class='card-panel grey lighten-4 z-depth-2 center'><p><strong>FELICIFIC</strong> is a journey which began last year.  With each passing year it grew and evolved and the abstract nothingness was molded into a definite  shape  with a purpose in mind. Years of tireless effort and dedicated endeavors, turned this into a legacy, a legacy which has been proudly carried by legions of students. <br><br> The purpose and the core ethics have remained static since the fest’s inception. To organize a fest with competitions designed to extract the best from students. Create an aura of aggressive competitiveness, and inculcate in the students a desire to excel and achieve what seems impossible. <br><br> The competitions, the excitement and the aggressiveness contributed in creating frenzy hitherto unseen. But all this will pale in comparison to FELICIFIC 13. Bigger, Better and Glitzier, FELICIFIC' 14 will be all that the previous version was much more. With many new competitions and the existing ones updated in sync with the latest technologies, this promises to be the ultimate battle of wits and As the FELICIFIC saga continues and with each step we soar to new heights, we remain grounded to our core values. So why worry about the destination when the journey can be so invigorating? Be a part of FELICIFIC and experience the awesome, spectacular, sublime, enthralling and everything you ever dreamed of. </p></div>"); 
        } 
        if(tgtbtnit == "about-ddu") {
          $("#knowmore").html("<div class='card-panel grey lighten-4 z-depth-2 center'><p> <strong>Dharmsinh Desai Foundation </strong>was established at Nadiad in Gujarat, by an eminent Parliamentarian and a social worker, Late Shri Dharmsinh Desai. This Foundation was established to develop institutions that would improve the quality of life for the people in and around Nadiad. Though it has schools, colleges, public library and hospitals under its umbrella, this note will essentially focus on the development and subsequent impact of Dharmsinh Desai University (DDU). From an affiliated college, started in 1968 as Dharmsinh Desai Institute of Technology (DDIT), offering Degree and Diploma in Chemical Engineering, DDU has now become a trusted name amongst a variety of stake holders, namely, students, their parents, researchers, academicians, employers, other academic institutions offering higher level education, National level Institutions and State & Central Government agencies. DDU (erstwhile DDIT) became the first Autonomous Institute in Gujarat State. Later, in the year of 2000, it was awarded a status of ‘Deemed University’ by Government of India, in recognition of its commendable standards in Academia. In April 2005, the Government of Gujarat declared this Institute as a ‘State University’. Recently Oxford Summit of Leaders has declared DDU as the Best Regional University. <br><br> DDU’s Vision is to become a multi-disciplined & ‘learner oriented’ university to closely associate with & be responsive to the Industry, to create supportive & caring environment for staff & students and to engage in R & D activities in areas of national priority. <br><br> DDU’s Mission is to undertake programs and projects for development of human resources, both through formal and non formal delivery systems, in areas of professional pursuits in all walks of human endeavors, with accent on relevance, value addition, societal needs and futuristic pilot projects. </p></div>"
            ); 
        }
      });
});